version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: username/repo:tag
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "${YOUR_FREE_HOST_PORT}:${PORT_INSIDE_YOUR_APP}"
    networks:
      - webnet
networks:
  webnet:
